# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-webserver-stream"
BBFILE_PATTERN_meta-webserver-stream = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-webserver-stream = "10"

LAYERDEPENDS_meta-webserver-stream = "core meta-python"
LAYERSERIES_COMPAT_meta-webserver-stream = "scarthgap"
